[platformio]
src_dir = .
default_envs = picow

[env:picow]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git#5d4561a05e3b212660ac6fdd3fbfb328d1988aa1
board = rpipicow
framework = arduino
board_build.core = earlephilhower
build_src_filter = +<main.cpp>
monitor_speed = 115200
lib_deps =
    adafruit/DHT sensor library@1.4.6
    adafruit/Adafruit Unified Sensor@1.1.15

[env:picow_rules]
extends = env:picow
build_flags = -DUSE_EXACT_RULES=1
